build:
    environment:
        php: 7.0.6
filter:
    paths: [src/*]
    excluded_paths: [tests/*, vendor/*, build/*, Resorces/*]
checks:
  php:
    code_rating: true
tools:
  php_analyzer:
    enabled: true
    extensions:
        - php
  external_code_coverage:
    timeout: 1200
    runs: 3
  php_code_coverage: false
  php_code_sniffer:
    config:
      standard: PSR2
    filter:
      paths: ['src']
  php_loc:
    enabled: true
    excluded_dirs: [vendor, spec]
  sensiolabs_security_checker:
    enabled: true
